### ISSUE TITLE
Add Apache License

### ISSUE THREAD

**Issue by itsmeadarsh2008** [tomasr8/pyjsx#1]
I'm recommending to use Apache License so, you can write `CHANGELOG.md`

**Comment by tomasr8** [comment]
I'm not that familiar with that license, any reason to favour that over the MIT license?

**Comment by tomasr8** [comment]
Added in https://github.com/tomasr8/pyjsx/commit/38da718fae4116b9cded8a74f7e91e9bf1187868 :)
